name: Deploy to Ghost Pro

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm run zip
    - name: Upload to Ghost
      run: |
        curl -X POST \
        "${{ secrets.GHOST_API_URL }}/themes/upload/" \
        -H "Authorization: Ghost ${{ secrets.GHOST_API_KEY }}" \
        -F "file=@dist/source.zip"
